//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelderWebSite01
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        public int ROBOT_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public string URL_NAME { get; set; }
        public string USUAL_NAME { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string IMAGE { get; set; }
    
        public virtual PRODUCTS_CATEGORY PRODUCTS_CATEGORY { get; set; }
    }
}
